In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"D:\ML\Scikit-Learn-Tutorial-\New ML\train (2).csv")[['Age','Pclass','SibSp','Parch','Survived']]

In [3]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [4]:
df.isnull().sum()

Age         177
Pclass        0
SibSp         0
Parch         0
Survived      0
dtype: int64

In [5]:
df = df.dropna()

In [6]:
df.isnull().sum()

Age         0
Pclass      0
SibSp       0
Parch       0
Survived    0
dtype: int64

In [7]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [8]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [9]:
X= df.iloc[:,0:4]
y = df.iloc[:,-1]

In [10]:
np.mean(cross_val_score(LogisticRegression(), X,y ,scoring='accuracy',cv=20))

np.float64(0.6933333333333332)

Applying Feature Construction

In [20]:
X['Family_size'] = X['SibSp'] + X['Parch'] + 1

In [21]:
df.sample(9)

      Age  Pclass  SibSp  Parch  Survived  Family_Size
423  28.0       3      1      1         0            3
782  29.0       1      0      0         0            1
555  62.0       1      0      0         0            1
273  37.0       1      0      1         0            2
228  18.0       2      0      0         0            1
361  29.0       2      1      0         0            2
677  18.0       3      0      0         1            1
694  60.0       1      0      0         0            1
24    8.0       3      3      1         0            5

In [22]:
def myfunc(num):
    if num == 1:
        #alone
        return 0
    elif num >1 and num <=4:
        # small family
        return 1
    else:
        # large family
        return 2

In [23]:
myfunc(5)

2

In [25]:
X['Family_type'] = X['Family_size'].apply(myfunc)

In [26]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size  Family_type
0  22.0       3      1      0            2            1
1  38.0       1      1      0            2            1
2  26.0       3      0      0            1            0
3  35.0       1      1      0            2            1
4  35.0       3      0      0            1            0

In [27]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

np.float64(0.7031746031746031)